<?php
/**
 * This class has been auto-generated by PHP-DI.
 */
class CompiledContainer extends DI\CompiledContainer{
    const METHOD_MAPPING = array (
  'core_string_manager' => 'get1',
  'core\\clock' => 'get2',
  'Psr\\Clock\\ClockInterface' => 'get3',
);

    protected function get1()
    {
        return $this->resolveFactory(static fn() => get_string_manager(), 'core_string_manager');
    }

    protected function get2()
    {
        return $this->resolveFactory(static fn() => new \core\system_clock(), 'core\\clock');
    }

    protected function get3()
    {
        return $this->delegateContainer->get('core\\clock');
    }

}
